# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Contemplations of an oblivious mind
description: >- # this means to ignore newlines until "baseurl:"
  <h1 style="color: #FFFFFF">I'm Bas</h1>I build security products at GitHub. I love data. In a previous life, I had
  fun with <a href="/pwahstacktc">graph algorithms</a>, wrote a <a href="https://ora.ox.ac.uk/objects/uuid:91aa418d-536e-472d-9089-39bef5f62e62">PhD thesis on probabilistic
  data</a>, and built <a href="http://paleolatitude.org">paleolatitude.org</a>. Every now and then I write
  my thoughts down here, or write some <a href="https://github.com/sj">code on GitHub</a>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sj.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bas_van_schaik
github_username:  sj

# Build settings
markdown: kramdown

theme: jekyll-theme-lanyon

paginate:            5
permalink:           pretty


plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
