name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main # or master before October 2020

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@64b759fc0e18682ff47a0522072df02762a76af2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
